version: '3.7'
services:
  model_predictor:
    image:  ${IMAGE_NAME}
    # restart: on-failure
    # build: 
    #   context: .
    volumes:
      - ./model_config:/model_config
      - ./src:/src
      - ../data:/data
    ports:
      - ${PORT}:8000
    # Docker containers communicate with services running on the host machine using the special host name host.docker.internal.
    environment:
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"

    entrypoint: /bin/sh -c "python /src/model_predictor.py"